<?php

namespace ContainerJa1iL2p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VPQzeANService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VPQzeAN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VPQzeAN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formedeboxe' => ['privates', '.errored..service_locator.VPQzeAN.App\\Entity\\Formedeboxe', NULL, 'Cannot autowire service ".service_locator.VPQzeAN": it needs an instance of "App\\Entity\\Formedeboxe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'formedeboxe' => 'App\\Entity\\Formedeboxe',
        ]);
    }
}
