<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formedeboxe extends \App\Entity\Formedeboxe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'club' => [parent::class, 'club', null],
        "\0".parent::class."\0".'commande' => [parent::class, 'commande', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'quantite' => [parent::class, 'quantite', null],
        "\0".parent::class."\0".'recapDetails' => [parent::class, 'recapDetails', null],
        'club' => [parent::class, 'club', null],
        'commande' => [parent::class, 'commande', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'photo' => [parent::class, 'photo', null],
        'prix' => [parent::class, 'prix', null],
        'quantite' => [parent::class, 'quantite', null],
        'recapDetails' => [parent::class, 'recapDetails', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
