<?php

namespace ContainerELJsLJQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLicenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rnxwCm0.App\Entity\Licence' shared service.
     *
     * @return \App\Entity\Licence
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rnxwCm0": it needs an instance of "App\\Entity\\Licence" but this type has been excluded in "config/services.yaml".');
    }
}
