<?php

namespace ContainerBuoX5N5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_71hrKCaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.71hrKCa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.71hrKCa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'licenceRepository' => ['privates', 'App\\Repository\\LicenceRepository', 'getLicenceRepositoryService', true],
        ], [
            'licenceRepository' => 'App\\Repository\\LicenceRepository',
        ]);
    }
}
