<?php

namespace ContainerBuoX5N5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLicenceFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LicenceFormType' shared autowired service.
     *
     * @return \App\Form\LicenceFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LicenceFormType.php';

        return $container->privates['App\\Form\\LicenceFormType'] = new \App\Form\LicenceFormType();
    }
}
