<?php

namespace Container4m3e3Xb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormedeboxeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VPQzeAN.App\Entity\Formedeboxe' shared service.
     *
     * @return \App\Entity\Formedeboxe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VPQzeAN": it needs an instance of "App\\Entity\\Formedeboxe" but this type has been excluded in "config/services.yaml".');
    }
}
