<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKlc7D6B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKlc7D6B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKlc7D6B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKlc7D6B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKlc7D6B\App_KernelDevDebugContainer([
    'container.build_hash' => 'Klc7D6B',
    'container.build_id' => '2451ebe2',
    'container.build_time' => 1711103370,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKlc7D6B');
