<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerELJsLJQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerELJsLJQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerELJsLJQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerELJsLJQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerELJsLJQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ELJsLJQ',
    'container.build_id' => 'd60e29df',
    'container.build_time' => 1711057014,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerELJsLJQ');
