<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xIJ2xQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xIJ2xQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4xIJ2xQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4xIJ2xQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4xIJ2xQ\App_KernelDevDebugContainer([
    'container.build_hash' => '4xIJ2xQ',
    'container.build_id' => '02f89e4d',
    'container.build_time' => 1710948121,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xIJ2xQ');
